# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)

enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
run_distribute: False
enable_profiling: False
dataset_path: "/cache/dataset/"
output_path: "/cache/output/"
load_path: "/cache/load_checkpoint/"
device_target: "Ascend"
log_save_path: "./log/"
checkpoint_save_path: "./checkpoint/"
checkpoint_file_path: "/cache/load_checkpoint/RPP-10_115.ckpt"
# =========================================================================

# dataset setting
mindrecord_dir: "./MindRecord"
dataset_name: "cuhk03"
batch_size: 1
num_parallel_workers: 4

# model setting
model_name: "RPP"
use_G_feature: True

# Export setting
image_height: 384
image_width: 128
file_name: "export_RPP_cuhk03_G"
file_format: "MINDIR"

# preprocess setting
preprocess_result_path: "./preprocess_Result"

# postprocessing setting
query_prediction_path: "./query_result_files"
gallery_prediction_path: "./gallery_result_files"
