model_type: 'classification'
is_modelarts: False
data_url: ''
train_url: ''

# platform configuration
device_id: 0
device_target: Ascend

# dataset configuration
dataset_type: 'ModelNet40'
dataset_path: ''
epoch_size: 200
batch_size: 32
num_points: 1024
uniform: False
use_normals: True
num_workers: 5

# checkpoint configuration
pretrain_ckpt: ""
save_checkpoint_path: './ckpt'

# training config
run_distribute: False
learning_rate: 0.05
weight_decay: 0.0001
enable_profiling: False
eval_proid: 1
eval_start: 80

#export config
file_name: "pointTrans_cls"
file_format: "MINDIR"