# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)

enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
run_distribute: False
enable_profiling: False
dataset_path: "/cache/dataset/"
output_path: "/cache/output/"
load_path: "/cache/load_checkpoint/"
device_target: "Ascend"
log_save_path: "./log/"
checkpoint_save_path: "./checkpoint/"
checkpoint_file_path: "/cache/load_checkpoint/pretrained_resnet50.ckpt"

#dataset setting
mindrecord_dir: "./MindRecord"
dataset_name: "cuhk03"
batch_size: 1
num_parallel_workers: 4
device_num: 1

#model setting
model_name: "PCB"

#optimizer setting
learning_rate: 0.1
lr_mult: 0.1
decay_rate: 0.1
momentum: 0.9
weight_decay: 5e-4
nesterov: True
frozen: False

#training setting
running_stage: "train"
mode_name: "GRAPH"
sink_mode: True
seed: 1
epoch_size: 10
step_size: 10
warmup: False
lr_mode: "constant"
loss_scale: 1.0

#checkpoint callbacks setting
save_checkpoint: True
save_checkpoint_epochs: 10
keep_checkpoint_max: 15

#EvalCallBack setting
run_eval: False
eval_interval: 15
eval_start_epoch: 60

use_G_feature: True

#Export setting
device_id: 0
image_height: 384
image_width: 128
file_name: "export_PCB_test"
file_format: "MINDIR"

#preprocess setting
preprocess_result_path: "./preprocess_Result"  

#postprocessing setting
query_prediction_path: "./query_result_files"
gallery_prediction_path: "./gallery_result_files"
