# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: True
device_target: Ascend
data_path: "/cache/data"
data_url: ""
train_url: ""
output_path: "/cache/out"

# ==============================================================================
# Training options
learning_rate: 0.001
epoch_size: 2
save_checkpoint_steps: 10
keep_checkpoint_max: 5
batch_size: 32
image_height: 28
image_width: 28
air_name: 'protonet.air'


# Model Description
model_name: protonet
file_name: 'protonet'
file_format: 'MINDIR'  # ['AIR', 'MINDIR']


---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'

device_target: 'Target device type'

---
device_target: ['Ascend', 'GPU', 'CPU']