# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unlesee you know exactly what you are doing)
use_modelarts: 0

# url for modelarts
data_url: ""
train_url: ""
outer_path: 's3://output/'

# mainly hyperparameters for training
noisetype: "gauss25"
n_feature: 48
n_channel: 3
lr: 3e-4
gamma: 0.5
epoch: 100
batch_size: 4
patchsize: 256
increase_ratio: 2.0

# dataset options, we recommend the absolute path
train_data: "/data/dataset"
test_dir: "/data/test_dataset"

# eval settings while training
eval_while_train: 1
eval_steps: 1
eval_start_epoch: 0

# checkpoint config while training
is_save_on_master: 1
output_path: './output/'
resume_path: ""
resume_name: ""

# eval settings stand alone, other hyperparameters are shared with training
pretrain_path: "./"
ckpt_name: "best_map.ckpt"
save_denoised_images: 1

# export settings stand alone, other hyperparameters are shared with training
dataset: "Kodak"
export_batch_size: 1
image_height: 512
image_width: 512
ckpt_file: "./best_map.ckpt"
file_name: "neighbor2neighbor"
file_format: "MINDIR"  # ["AIR", "MINDIR"]

# ======================================================================================
# common options
device_target: 'Ascend'
is_distributed: 0
rank: 0
group_size: 1
log_interval: 10


---
# Help description for each configuration
use_modelarts: "Whether training on modelarts, 1 for True, 0 for False; default: 0"
data_url: "needed by modelarts, but we donot use it because the name is ambiguous"
train_url: "needed by modelarts, but we donot use it because the name is ambiguous"
outer_path: "obs path,to store e.g ckpt files"
noisetype: "noise type"
n_feature: "n_feature"
n_channel: "n_channel"
lr: "lr"
gamma: "gamma"
epoch: "epoch"
batch_size: "batch_size"
patchsize: "patchsize"
increase_ratio: "increase_ratio"
train_data: "train_data"
test_dir: "test_dir, it should be the root path of image folders instead of root path of images"
eval_while_train: "Whether eval while training, 1 for True, 0 for False; default: 1"
eval_steps: "each N epochs we eval"
eval_start_epoch: "eval_start_epoch"
is_save_on_master: "save ckpt on master or all rank"
output_path: "output_path,when use_modelarts is set 1, it would better be cache/output/"
resume_path: "put the path to resuming file if needed"
resume_name: "resuming file name"
pretrain_path: "path of the ckpt to eval"
ckpt_name: "name of the ckpt to eval"
save_denoised_images: "Whether to save the denoised images when eval, 1 for True, 0 for False"
export_batch_size: "batch size for export ckpt"
image_height: "image height for export ckpt"
image_width: "image width for export ckpt"
ckpt_file: "the ckpt to export"
file_name: "name of exported ckpt"
file_format: "file format, choose from ['MINDIR','AIR','ONNX']"
device_target: "device where the code will be implemented. (Default: Ascend)"
is_distributed: "Whether multi device"
rank: "local rank of distributed"
group_size: "world size of distributed"
log_interval: "Logging interval steps"
