# model
name: 'osnet_x1_0'
pretrained: True
device_target: "Ascend"

# data
source: 'market1501'
target: 'market1501'
workers: 12
height: 256
width: 128
transforms: ['random_flip','random_erase']
norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]
cuhk03_labeled: False
cuhk03_classic_split: False
use_metric_cuhk03: False

# train
optim: 'adam'
lr: 0.001
weight_decay: 0.0005
max_epoch: 250
start_epoch: 10
start_step: 0
batch_size_train: 128
fixbase_epoch: 10
open_layers: ['classifier']
lr_scheduler: 'cosine'
stepsize: [20]
gamma: 0.1
print_freq: 20
loss_scale: 1024
save_checkpoint: True
save_checkpoint_epochs: 10
pretrained_dir: 'model_utils'
run_distribute: False
LogSummary: False

# optimizer
adam_beta1: 0.9
adam_beta2: 0.99

# loss
label_smooth: True

# eval
batch_size_test: 300
dist_metric: 'euclidean'
normalize_feature: False
ranks: [1, 5, 10, 20]
checkpoint_file_path: ""

# model_arts
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
enable_profiling: False
data_path: "/cache/data"
output_path: "/cache/train"
load_path: ""
checkpoint_path: "./checkpoint/"
need_modelarts_dataset_unzip: True

# export option
ckpt_file: ""
file_name: "osnet"
file_format: "MINDIR"