# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
is_distributed: False
# Path for local or modelarts
data_path: "~/NIMA/data/"
label_path: "~/NIMA/AVA.txt"
output_path: "s3://~output/"

# ==============================================================================
# options
device_target: "Ascend"
dataset_name: "AVA_Dataset"
batch_size: 256
epoch_size: 50
num_parallel_workers: 16
learning_rate: 0.001
momentum: 0.95
weight_decay: 0.001
bf_crop_size: 256
image_size: 224
train_label_path: "~/NIMA/AVA_train.txt"
val_label_path: "~/NIMA/AVA_test.txt"
keep_checkpoint_max: 10
checkpoint_path: "~/NIMA/model/resnet50_ascend_v130_imagenet2012_official_cv_bs256_top1acc76.97__top5acc_93.44.ckpt"
ckpt_filename: "NIMA"
ckpt_save_dir: "./model/"
device_id: 0

# eval or export option
val_data_path: "~/NIMA/test_data/"
ckpt_file: "~/NIMA/model/NIMA-2_898.ckpt"
file_name: "NIMA"
file_format: "MINDIR"
file_save: "./model/"

---

# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
is_distributed: "Whether training use multiple cards, default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
output_path: "The location of the output file that uses modelarts."
data_path: "The location of the input data."
device_target: 'Target device type'
enable_profiling: 'Whether enable profiling while training, default: False'
